version: "3.8"
services:
  accesspoint-db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: formforge
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
